In [1]:
import pandas as pd
from matplotlib import pyplot as plt
import numpy as np
import math
import seaborn as sns
import sklearn
from sklearn import linear_model
from sklearn import preprocessing
%matplotlib inline
sns.set_style('white')

Using this credit card fraud dataset develop an algorithm to predict fraud. Prioritize correctly finding fraud rather than correctly labeling non-fraudulent transactions.

It contains only numerical input variables which are the result of a PCA transformation. Unfortunately, due to confidentiality issues, we cannot provide the original features and more background information about the data. Features V1, V2, ... V28 are the principal components obtained with PCA, the only features which have not been transformed with PCA are 'Time' and 'Amount'. Feature 'Time' contains the seconds elapsed between each transaction and the first transaction in the dataset. The feature 'Amount' is the transaction Amount, this feature can be used for example-dependant cost-senstive learning. Feature 'Class' is the response variable and it takes value 1 in case of fraud and 0 otherwise.

In [2]:
df = pd.read_csv('creditcard.csv')

In [3]:
df.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...         V21       V22       V23       V24  \
0  0.098698  0.363787  ...   -0.018307  0.277838 -0.110474  0.066928   
1  0.085102 -0.255425  ...   -0.225775 -0.638672  0.101288 -0.339846   
2  0.247676 -1.514654  ...    0.247998  0.771679  0.909412 -0.689281   
3  0.377436 -1.387024  ...   -0.108300  0.005274 -0.190321 -1.175575   
4 -0.270533  0.817739  ...   -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28  Amount  Class  
0  0.128539 -0.189115  0.133558 -0.021053  149.62      0  
1  0.167170  0.125895 -0.008983  0.014724    2.69      0  
2 -0.327642 -0.139097 -0.055353 -0.059752  378.66      0  
3  0.647376 -0.221929  0.062723  0.061458  123.50      0  
4 -0.206010  0.502292  0.219422  0.215153   69.99      0  

[5 rows x 31 columns]

In [4]:
df.shape

(284807, 31)

### Class = 1 for Fraudulent, 0 otherwise

In [5]:
# Random forest

In [6]:
from sklearn import ensemble
from sklearn.model_selection import cross_val_score

rfc = ensemble.RandomForestClassifier(n_jobs=-1)
X = df.drop('Class', 1)
Y = df['Class']
X = X.dropna(axis=1)

/usr/local/lib/python3.6/site-packages/sklearn/ensemble/weight_boosting.py:29: DeprecationWarning: numpy.core.umath_tests is an internal NumPy module and should not be imported. It will be removed in a future NumPy release.
  from numpy.core.umath_tests import inner1d


In [7]:
cross_val_score(rfc, X, Y, cv=10)

array([0.0436416 , 0.9989467 , 0.99982444, 0.99947333, 0.999052  ,
       0.99901685, 0.99982444, 0.99950843, 0.99936798, 0.99929775])

In [8]:
# very good except for the first one, which was very bad

In [9]:
X.head()

Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9   ...         V20       V21       V22       V23  \
0  0.098698  0.363787   ...    0.251412 -0.018307  0.277838 -0.110474   
1  0.085102 -0.255425   ...   -0.069083 -0.225775 -0.638672  0.101288   
2  0.247676 -1.514654   ...    0.524980  0.247998  0.771679  0.909412   
3  0.377436 -1.387024   ...   -0.208038 -0.108300  0.005274 -0.190321   
4 -0.270533  0.817739   ...    0.408542 -0.009431  0.798278 -0.137458   

        V24       V25       V26       V27       V28  Amount  
0  0.066928  0.128539 -0.189115  0.133558 -0.021053  149.62  
1 -0.339846  0.167170  0.125895 -0.008983  0.014724    2.69  
2 -0.689281 -0.327642 -0.139097 -0.055353 -0.059752  378.66  
3 -1.175575  0.647376 -0.221929  0.062723  0.061458  123.50  
4  0.141267 -0.206010  0.502292  0.219422  0.215153   69.99  

[5 rows x 30 columns]

# Decision Tree/Random Forest

In [10]:
CLASS = df['Class']

In [11]:
features = X.columns
rfc.fit(X, Y)
importances = rfc.feature_importances_
indices = np.argsort(importances)

In [12]:
for feature in zip(features, rfc.feature_importances_): 
    print(feature)

('Time', 0.017853836837832225)
('V1', 0.01414336716795542)
('V2', 0.012114838178640404)
('V3', 0.014654421123663561)
('V4', 0.023247862606125137)
('V5', 0.01184124035701278)
('V6', 0.02441041769720651)
('V7', 0.028504652907942636)
('V8', 0.009239506080485372)
('V9', 0.04377628736053521)
('V10', 0.10251334428786052)
('V11', 0.040986303757414404)
('V12', 0.201260565163548)
('V13', 0.011838081020824011)
('V14', 0.0958437408557983)
('V15', 0.009633179618076247)
('V16', 0.025776531392481254)
('V17', 0.1780904284074797)
('V18', 0.014478051680700016)
('V19', 0.009168729983367579)
('V20', 0.009454209506959351)
('V21', 0.013492054108008522)
('V22', 0.007135514116565068)
('V23', 0.013959824115871489)
('V24', 0.006483171611035723)
('V25', 0.008935217742309941)
('V26', 0.01781753163565714)
('V27', 0.009561905120844528)
('V28', 0.013294254620695029)
('Amount', 0.010490930937103854)


In [13]:
df_2 = df[['V1', 'V2', 'V3', 'V4', 'V5', 'V6', 'V7', 'V8', 'V9']]

In [14]:
from sklearn import tree

# Packages for rendering our tree.
import pydotplus
import graphviz

# Initialize and train our tree.
decision_tree = tree.DecisionTreeClassifier(
    criterion='entropy',
    max_features=1,
    max_depth=4,
)
decision_tree.fit(df_2, CLASS)

DecisionTreeClassifier(class_weight=None, criterion='entropy', max_depth=4,
            max_features=1, max_leaf_nodes=None, min_impurity_decrease=0.0,
            min_impurity_split=None, min_samples_leaf=1,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=None, splitter='best')

In [15]:
cross_dc = cross_val_score(decision_tree, df_2, CLASS, cv=10)

In [16]:
cross_dc

array([0.99799874, 0.99898181, 0.99919244, 0.99852533, 0.99817422,
       0.99824438, 0.99940309, 0.99856039, 0.99841994, 0.99824438])

In [17]:
rfc = ensemble.RandomForestClassifier(n_jobs= -1)
X = df_2
Y = CLASS
X = X.dropna(axis=1)


In [18]:
cross_rf = cross_val_score(rfc, X, Y, cv=10)

In [19]:
cross_rf

array([0.99834983, 0.99880626, 0.99957867, 0.99877111, 0.99856044,
       0.99894663, 0.9994382 , 0.99901685, 0.99905197, 0.99894663])

In [20]:
# df['Time'] was giving the single, very low cross_val score.  Dropping it improved the results.

In [21]:
# Import the model.
from sklearn.neural_network import MLPClassifier

# Establish and fit the model, with a single, 1000 perceptron layer.
mlp = MLPClassifier(hidden_layer_sizes=(1000,))
# mlp = MLPClassifier(hidden_layer_sizes=(100,))
# mlp = MLPClassifier(hidden_layer_sizes=(100,4))
mlp.fit(X, Y)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(1000,), learning_rate='constant',
       learning_rate_init=0.001, max_iter=200, momentum=0.9,
       nesterovs_momentum=True, power_t=0.5, random_state=None,
       shuffle=True, solver='adam', tol=0.0001, validation_fraction=0.1,
       verbose=False, warm_start=False)

In [22]:
mlp.score(X, Y)

0.9993469261640339

In [23]:
# mlp = MLPClassifier(hidden_layer_sizes=(100,))
# mlp.score(X,Y)
# 0.9993083035178209

In [24]:
# mlp = MLPClassifier(hidden_layer_sizes=(100,4))
# mlp.score(X,Y)
# 0.9993399038647224

In [25]:
Y.value_counts()/len(Y)

0    0.998273
1    0.001727
Name: Class, dtype: float64

In [26]:
# mlp = MLPClassifier(hidden_layer_sizes=(100,))
# mlp = MLPClassifier(hidden_layer_sizes=(100,4))
# Y.value_counts()/len(Y)
# 0    0.998273
# 1    0.001727
# Name: Class, dtype: float64

In [27]:
cross_val_score(mlp, X, Y, cv=5)

array([0.99884133, 0.99949089, 0.99889398, 0.99949088, 0.99919243])

In [28]:
# mlp = MLPClassifier(hidden_layer_sizes=(100,))
# array([0.998736  , 0.99924511, 0.99892909, 0.99945577, 0.99926265])

In [29]:
# mlp = MLPClassifier(hidden_layer_sizes=(100,4))
# array([0.99875356, 0.99945578, 0.99885887, 0.99936799, 0.99935043])

Since this dataset was reduced down to 9 features, MLP and Random Forest performed similarly.  MLP took longer when using 1000 layer sizes.  Accuracy was very good for both models.